### ISSUE TITLE
What do you think about using my dbusmenu?

### ISSUE THREAD

**Issue by rilian-la-te** [equeim/xfce4-snw-plugin#8]
Using my dbusmenu module allows you to get rid from DbusmenuGtk dependency (My module is a git submodule, no shlib).
And I, instead of canonical, can add new features or fix bugs. (Canonical calls Dbusmenu deprecated)
I have one extension into my module - slider-type menu items (like used in Xfce Power Manager).
Next limitation - with my module you need to provide GLib 0.27 vapi (for bugfix reasons)

**Comment by equeim** [comment]
GTK+ 2 support is essential for my plugin.

> Canonical calls Dbusmenu deprecated

As far as I know, Canonical use it in their indicator-application, SNI applet for Unity panel.

**Comment by rilian-la-te** [comment]
AFAIK, my dbusmenu builds in GTK2, it requires GLib 2.40:-)
Yes, canonical used it, but in notes it states about deprecation.

**Comment by equeim** [comment]
> AFAIK, my dbusmenu builds in GTK2, it requires GLib 2.40:-)

```
test.vala:117.25-117.30: error: `Object' is an ambiguous reference between `GLib.Object' and `Gtk.Object'
    public class Item : Object
                        ^^^^^^
test.vala:15.30-15.35: error: `Object' is an ambiguous reference between `GLib.Object' and `Gtk.Object'
    public interface Iface : Object
                             ^^^^^^
test.vala:421.37-421.42: error: `Object' is an ambiguous reference between `GLib.Object' and `Gtk.Object'
    public interface GtkItemIface : Object
                                    ^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
```

I replaced Object by GLib.Object and got following errors:

```
gtk+-2.0.vapi:5875.40-5875.42: warning: Gtk is deprecated. Use gtk+-3.0
test.vala:435.33-435.35: warning: Gdk is deprecated. Use gdk-3.0
test.vala:437.33-437.35: warning: Gdk is deprecated. Use gdk-3.0
test.vala:439.33-439.35: warning: Gdk is deprecated. Use gdk-3.0
test.vala:441.33-441.35: warning: Gdk is deprecated. Use gdk-3.0
test.vala:467.19-467.52: error: 2 extra arguments for `void Gtk.Box.new ()'
            box = new Box(Orientation.HORIZONTAL, 5);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:507.44-507.46: warning: Gtk is deprecated. Use gtk+-3.0
test.vala:696.19-696.51: error: 2 extra arguments for `void Gtk.Box.new ()'
            box = new Box(Orientation.HORIZONTAL,5);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:699.22-699.58: error: 2 extra arguments for `void Gtk.Scale.new ()'
            slider = new Scale(Orientation.HORIZONTAL,adj);
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:700.13-700.26: error: The name `hexpand' does not exist in the context of `Gtk.Scale'
            slider.hexpand = true;
            ^^^^^^^^^^^^^^
test.vala:710.30-710.32: warning: Gdk is deprecated. Use gdk-3.0
test.vala:711.30-711.32: warning: Gdk is deprecated. Use gdk-3.0
test.vala:712.30-712.32: warning: Gdk is deprecated. Use gdk-3.0
test.vala:774.26-774.30: error: Argument 1: Cannot convert from `Gdk.EventButton' to `Gdk.Event'
            slider.event(event);
                         ^^^^^
test.vala:781.27-781.31: error: Argument 1: Cannot convert from `Gdk.EventButton' to `Gdk.Event'
            slider.event (event);
                          ^^^^^
test.vala:785.41-785.44: warning: Argument 1: Cannot pass null to non-null parameter type
                this.grab_broken_event (null);
                                        ^^^^
test.vala:791.27-791.31: error: Argument 1: Cannot convert from `Gdk.EventMotion' to `Gdk.Event'
            slider.event (event);
                          ^^^^^
test.vala:796.27-796.31: error: Argument 1: Cannot convert from `Gdk.EventScroll' to `Gdk.Event'
            slider.event (event);
                          ^^^^^
test.vala:816.19-816.52: error: 2 extra arguments for `void Gtk.Box.new ()'
            box = new Box(Orientation.HORIZONTAL, 5);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:857.44-857.46: warning: Gtk is deprecated. Use gtk+-3.0
test.vala:913.13-913.32: error: The name `set_accel' does not exist in the context of `Gtk.AccelLabel'
            this.label.set_accel(key,mod);
            ^^^^^^^^^^^^^^^^^^^^
test.vala:922.36-922.38: warning: Gtk is deprecated. Use gtk+-3.0
test.vala:831.13-831.36: error: The name `set_accessible_role' does not exist in the context of `DBusMenu.GtkMenuBarItem'
            this.set_accessible_role(Atk.Role.MENU_ITEM);
            ^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:545.17-545.40: error: The name `set_accessible_role' does not exist in the context of `DBusMenu.GtkMainItem'
                this.set_accessible_role(Atk.Role.RADIO_MENU_ITEM);
                ^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:551.17-551.40: error: The name `set_accessible_role' does not exist in the context of `DBusMenu.GtkMainItem'
                this.set_accessible_role(Atk.Role.CHECK_MENU_ITEM);
                ^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:557.17-557.40: error: The name `set_accessible_role' does not exist in the context of `DBusMenu.GtkMainItem'
                this.set_accessible_role(Atk.Role.MENU_ITEM);
                ^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:589.13-589.32: error: The name `set_accel' does not exist in the context of `Gtk.AccelLabel'
            this.label.set_accel(key,mod);
            ^^^^^^^^^^^^^^^^^^^^
test.vala:598.36-598.38: warning: Gtk is deprecated. Use gtk+-3.0
test.vala:643.9-643.46: error: overriding method `DBusMenu.GtkMainItem.draw_indicator' is incompatible with base method `Gtk.CheckMenuItem.draw_indicator': incompatible type of parameter 1.
        protected override void draw_indicator(Cairo.Context cr)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.vala:646.37-646.38: error: Argument 1: Cannot convert from `Cairo.Context' to `Gdk.Rectangle'
                base.draw_indicator(cr);
                                    ^^
test.vala:643.9-643.46: error: DBusMenu.GtkMainItem.draw_indicator: no suitable method found to override
        protected override void draw_indicator(Cairo.Context cr)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 18 error(s), 13 warning(s)
```

GLib version is 2.42. What am I doing wrong?

**Comment by rilian-la-te** [comment]
Will see this errors.

**Comment by rilian-la-te** [comment]
Can you tell me an advantages of manual DBus proxy?

**Comment by equeim** [comment]
As far as I know, there is no way to get changed properties from proxy object created by GLib.Bus.get_proxy_sync() function, it always gets them from cache. Creating new proxy every time when NewIcon/NewToolTip signals are emitted highly increases DBus traffic. So i just created class that manually invokes standard DBus methods and connects to signals.

**Comment by rilian-la-te** [comment]
OK, it is reasonable. But it has one standard DBUS method GetProperty. Proxy can be created for it and properties can be grabbed directly without cache.
